### PR TITLE
Take WiFi patches from Asahi Linux to read OTP

### PR DESCRIPTION
**Pull request by Redecorating**
This means firmware will be selected automatically. These patches also
fix a couple of bugs and make a few optimisations.

For this firmware selection:
```
 # in macos (or linux if you have a copy of the wifi folder):
git clone https://github.com/AsahiLinux/asahi-installer --depth=1
cd asahi-installer/src
python3 -m firmware.wifi /usr/share/firmware/wifi firmware.tar
 # in linux
cd /lib/firmware
sudo tar xf /path/to/firmware.tar
```
or you can use this https://cdn.discordapp.com/attachments/595304521857630259/923542180608475166/firmware.tar.gz

### CODE REVIEW

**Comment by Redecorating** [comment]
oh i just messed up the git history

**Comment by Redecorating** [comment]
there will be a third version of this wifi patchset soon so it might be better to wait for that

**Comment by jamlam** [comment]
Thanks, I've not actually got my mbb16 any more but I'm happy to keep taking pulls for this if it's still useful

**Comment by Redecorating** [comment]
That's patches from the https://github.com/AsahiLinux/linux/tree/wifi/take3 branch, which should use the correct mac address. There might be a take4, but that would only affect M1 pro/max, so it wouldn't be important for us.

**Comment by Redecorating** [comment]
that's take4, which it turns out might help bcm4377

**Pull request merged**
